### ISSUE TITLE
WHITEbeet Carrier Board (EVSE) V2G SetConfiguration Failure

### ISSUE THREAD

**Issue by Bobbybigears** [Sevenstax/FreeV2G#112]
Hi,
I'm currently developing a charging application using a WHITEbeet Carrier Board (EV) (WB-CARRIER-BOARD-PI 1.1). The board is configured for SPI communications. I'm also using a WHITEbeet Carrier Board (EVSE) (WB-CARRIER-BOARD-E1 1.1) to represent the charging station for initial development.
I've connected the two WHITEbeet's together via the Control Pilot and Protective Earth inputs. 
I'm using a Raspberry Pi Model 4B to connect to the EVSE board using the latest code in the repository, i.e. the code which is cloned via 'git clone'. 
The interaction between the two WHITEbeet boards works fine until the EVSE board tries to set the V2G configuration (mod-id 0x27, sub_id 0x60) when it reports a response/acknowledgement code of 0x04 (malformed data) and exits. At this stage the EV board hasn't sent any V2G commands.  I didn't have a camera handy to capture the screen, so I typed the output from the Python Script in to a .txt file. This is attached.
I would be most grateful for any help you can provide with regard to this issue.
Best regards
Rob
[whitebeet.txt](https://github.com/Sevenstax/FreeV2G/files/10164205/whitebeet.txt)

**Comment by jpo-stx** [comment]
The latest FreeV2G application from the master branch works with the latest version of the Whitebeet, which is firmware version 2.0.1 and since we changed the host controller interface (HCI) between 1.1.7 and 2.0.1 you get the error for the configuration message.
I would recommend that you update your Whitebeet to the latest firmware version. But you can also use the correct tag of the repository that fits your firmware version https://github.com/Sevenstax/FreeV2G/tags. In your case that would be https://github.com/Sevenstax/FreeV2G/tree/EVSE_v1.1.7_1.
