### ISSUE TITLE
Stop communication after Service Discovery Response if supported application Protocol selected ISO15118

### ISSUE THREAD

**Issue by nikunjp26** [Sevenstax/FreeV2G#173]
Platform: PEV / EVSE
Firmware Version: i.e. V02_00_01
Host Controller Interface: Ethernet / SPI
Host: Own development

We have integrated Whitebeet module running EVSE firmware version V02.00.01 with our CCS2 charger with single gun only. we connect only single Whitebeet module on the Ethernet with Mahindra XUV400 EV Car. Communication is stopping after **Service Discovery Response** if supported application Protocol selected was ISO15118.

Please find the attached logs which capture using the Greenshark

[xuv_ISO15118_Selected.zip](https://github.com/Sevenstax/FreeV2G/files/11273888/xuv_ISO15118_Selected.zip)

**Comment by nststx** [comment]
Hi @nikunjp26,

Thanks for submitting your issue. I will take a look at it in the upcoming days and come back to you until the end of this week.

Best regards,
Niklas Stoffers

**Comment by nststx** [comment]
Hi @nikunjp26,

I've taken a look at the Wireshark logs and so far I don't see a reason why the EV is not responding after the Service Discovery Response. All exchanged parameters are normal and timeout requirements are met. Could you capture a UART log of the Whitebeet to help me investigate this issue further?

Best regards,
Niklas Stoffers

**Comment by nikunjp26** [comment]
Dear Niklas,

Please find the logs of debug uart.
[teraterm (2).log](https://github.com/Sevenstax/FreeV2G/files/11351388/teraterm.2.log)


Regards,
Nikunj Patel

**Comment by nststx** [comment]
Hi @nikunjp26,

I took another look at the logs with a colleague today and we're still not sure why the session doesn't continue after the ServiceDiscoveryResponse. We currently suspect that the problem is actually on the car side and not on the charger side. If you take a look at the SessionSetupReq that the car sends there's already an issue with it. The ISO standard requires the car to send a SessionSetupReq with a session id of 0 for new sessions. However the car sends some session id so maybe it just got stuck in a weird state?

However just to be sure that I'm not missing something could you capture another Wireshark log charging the car with DIN? Maybe this we find something in there that helps with the issue.

Best regards,
Niklas Stoffers

**Comment by nikunjp26** [comment]
Dear Niklas,

We don't have "Mahindra XUV400 EV Car" now. We will capture the logs when this car will be available and provide to you.

Thanks & Best Regards,
Nikunj Patel

**Comment by nikunjp26** [comment]
Dear Niklas,

[xuv400_1.zip](https://github.com/Sevenstax/FreeV2G/files/12013957/xuv400_1.zip)
Please find the attached wireshark log file which we captured again today.

Thanks & Best Regards,
Nikunj Patel

**Comment by nststx** [comment]
Hi @nikunjp26,

Thanks for coming back with the logs. I will take a look at them in the upcoming days and let you know what I've found out.

Best regards,
Niklas Stoffers

**Comment by nststx** [comment]
Hi @nikunjp26,

I've taken a look at your logs. However I do not find a V2G session in there (furthest step was SECCDP). Could you please capture another log with your charger and the car using DIN70121? Please make sure that the Whitebeet is directly connected without a network switch or something in between so that no packets are lost. Also do you have some sort of debug information from the car when a charging session is failing?

Best regards,
Niklas Stoffers

**Comment by nikunjp26** [comment]
Dear Niklas,

We had many times charge our Hyundai KONA which is supporting the DIN70121 protocol. till now we didn't face any issue with that car. 

can we load the "Sevenstax_WHITEBEET_ISO15118_EVSE_EIM_V01_01_07" firmware inside the whitebeet module? right now we are using the "02.01.00_PNC" firmware now? this is just for the testing only.

Best Regards,
Nikunj Patel

**Comment by nststx** [comment]
Hi @nikunjp26,

Although it's possible to downgrade your EVSE Whitebeet to V01_01_07 I wouldn't advise to do that. The V01_01_07 contains bugs which we fixed in newer version and it also uses our old API. Thus the V01_01_07 would also not be compatible with your host implementation as our API had quite a few changes between V01 and V02. May I ask why you want to try the V01_00_07 firmware?

Best regards,
Niklas Stoffers

**Comment by nikunjp26** [comment]
Dear Niklas,
> May I ask why you want to try the V01_00_07 firmware?
We have some chargers deployed in the field, and customers and users are complaining again and again to us and we don't have a solution right now. We can use this firmware now temporarily If this older version works for us.

Best Regards,
Nikunj Patel

**Comment by nststx** [comment]
Hi @nikunjp26,

You can try using the V01_01_07 firmware. However it will probably not be compatible with your current host implementation as the API changed a lot between V01 and V02.

Do you maybe have a log of a Mahindra XUV charging successfully?

Best regards,
Niklas Stoffers

**Comment by nikunjp26** [comment]
Dear Niklas,

we tried to test the xuv today but unfortunately not able do any single success transaction. due to that our customer is frustrate now. 
please look into that and guide if we can do any best as we are helpless right now.

[XUV_250723.zip](https://github.com/Sevenstax/FreeV2G/files/12161695/XUV_250723.zip)

best regards,
Nikunj Patel

**Comment by nikunjp26** [comment]
Dear Niklas,

We also tried with Nextion new car today and socket close after the charge parameter discovering request.

[nextion_260723.zip](https://github.com/Sevenstax/FreeV2G/files/12169201/nextion_260723.zip)

best regards,
nikunj patel

**Comment by nststx** [comment]
Hi @nikunjp26,

Thanks for the new logs. I will need some more time to look into them and come back to you once I've got an update.

Best regards and thanks for your patience,
Niklas Stoffers

**Comment by nststx** [comment]
Hi @nikunjp26,

I've taken a look at your logs. The car doesn't comply to the message timeouts defined in the ISO standard. It only waits about 400ms for the ChargeParameterDiscoveryResponse. However since you haven't set the schedules yet the Whitebeet will wait 1500ms to send the ChargeParameterDiscoveryResponse with Processing Status "Ongoing" to prevent unnecessary message exchanges. This timeout is compliant with the ISO standard. 

You should be able to do a workaround for this issue by setting the schedules immediately after they are requested by the Whitebeet. However note that the whole process has to take less than 400ms so the car doesn't close the TCP connection.

Please let me know if the proposed solution works for you!

Best regards,
Niklas Stoffers

**Comment by nststx** [comment]
Hi @nikunjp26,

I've taken a look at your Tata Nexon logs. Please take a look at #170. Regarding the logs from Mahindra, I will need some more time to look into them. I'll let you know once I've got an update.

Best regards and thanks for your patience,
Niklas Stoffers

**Comment by nststx** [comment]
Deleted Nextion logs from this issue and moved them to #196 as things got a little bit too mixed up here.

**Comment by nikunjp26** [comment]
Dear Niklas,

any update on this?

Best Regards,
Nikunj Patel

**Comment by lho-stx** [comment]
Hey @nikunjp26,

in packet 3950 the EV sends a session stop request. This is not allowed at this point. There is also no reason to do this (from a protocol viewpoint), all timeouts are met. You resolved #196 by improving your CP cabling, may this a solution for this issue too, as these are highly similar?

Best regards,
lho

**Comment by nikunjp26** [comment]
Dear Iho,
We will check with the CAR Again and reply back.

Best Regards,
Nikunj Patel

**Comment by nikunjp26** [comment]
Dear Iho,
We checked with a CAR and able charge it. If finding any problems, we will get back to you.

Best Regards,
Nikunj Patel

**Comment by nikunjp26** [comment]
Dear Iho & Team,

We are closing this as it is workign now.
