### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by JimZuber** [Sevenstax/FreeV2G#221]
I have  EV and EVSE White Beet boards talking to each other using FreeV2G. While the log messages via the Linux terminal console and the carrier board serial interface are useful, what I would really like is to see the 15118 message traffic pushed up to the application layer so that it could be captured.  I looked through the White Beet documentation and didn't see an obvious way to do this. Is there some undocumented what to make this happen or do you have to play one end of the communication link or use a protocol analyzer to capture the traffic?

Thanks,

Jim ZUber
Qualitylogic, Inc.

**Comment by nststx** [comment]
Hi @JimZuber,

Thanks for submitting your question. If you want to take a look at the V2G communication you can activate the port mirror to do so. Enabling port mirror will effectively mirror the PLC traffic onto the WhiteBeets Ethernet interface. If you're using the latest version of FreeV2G you can simply enable the port mirror with the `--portmirror` command line argument. Please make sure that your WhiteBeet is directly connected to your PC (no network switch inbetween) as you won't be able to see the mirrored packets otherwise.

I hope I could clarify your question. If you have any more questions or need further guidance on how to capture the traffic using port mirror, please let me know!

Best regards,
Niklas Stoffers
