### ISSUE TITLE
Charging Issue: EV Target Current Fluctuate Over Time

### ISSUE THREAD

**Issue by GovindMore** [Sevenstax/FreeV2G#257]
**Your Setup**
Platform: EVSE
Firmware Version: i.e. V02_01_00
Host Controller Interface: Ethernet 
Host: FreeV2G (EV_v2.1.0_1) 

**Describe the bug**
While charging the Tata Tiago, one of the following two scenarios occurs, and the charging stops:

Case 1: After charging for a few seconds, the EV target current suddenly starts to drop, and then "Request stop charging" is received.

Case 2: After charging for a few seconds, the EV target current fluctuates. For example, it may increase to 38A and then drop to 3A, before rising to 40A again. This fluctuation ultimately leads to charging being interrupted with Error Code 5.

Terminal logs and wireshark logs for both cases are attached.

**Logs**

[case_2.txt](https://github.com/Sevenstax/FreeV2G/files/13233060/case_2.txt)
[case2_wireshark.txt](https://github.com/Sevenstax/FreeV2G/files/13233063/case2_wireshark.txt)
[case1_wireshark.txt](https://github.com/Sevenstax/FreeV2G/files/13233064/case1_wireshark.txt)
[case_1.txt](https://github.com/Sevenstax/FreeV2G/files/13233065/case_1.txt)

**Comment by lho-stx** [comment]
Hey @GovindMore,

can you please enable the port mirror feature and recreate the logs? This would help a lot in identifying the problem. The problem is most likely not related to the Whitebeet firmware itself, because the values are just reported from/to the host application. To identify the problem I need the V2G traffic in the log files too.

Best regards,
lho
