### ISSUE TITLE
Question: Charging 2 EVs with one host but one of them stop charging after.

### ISSUE THREAD

**Issue by sametyazici** [Sevenstax/FreeV2G#279]
We try to charge 2 EVs with 2 PLC module. Both start charging but after 30 seconds one of them stop charging. We deactivated port mirroring for both PLC but it does not solve our problem. As recomended we establish VLANs but it does not work to. What would you suggest to us?

**Comment by lho-stx** [comment]
Hey @sametyazici,

if you have problems please use this template for creating an issue:

https://github.com/Sevenstax/FreeV2G/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Please add all relevant information to the template.

Using Whitebeet with VLANs is not officially supported, but I can give some thoughts about this setup. Whitebeet does not support tagged VLANs, therefore you need physical separation between them. You may use a tagged VLAN between your Host PC and a managed switch. The switch needs to forward the tagged traffic as untagged traffic to different physical outlets. The switch needs to tag the traffic coming from the Whitebeet to the Host PC and untag the traffic from the Host PC to the Whitebeet. On the host PC you need different network interfaces for the different Whitebeets.

Please take my advice with a grain of salt, because I did not test this setup!

Best regards,
lho
