### ISSUE TITLE
Charging stops when second EV connected to the host.

### ISSUE THREAD

**Issue by sametyazici** [Sevenstax/FreeV2G#281]
**Your Setup**
Platform: PEV / EVSE
Firmware Version: i.e. V02_10_1
Host Controller Interface: Ethernet 
Host: Own Implementation

**Describe the bug**
We try to charge 2 EVs with 2 whitebeet and single host. One of them is charging properly but other  stops 30 second after charging starts. We are using raspberry pi. We are using its ethernet interface and usb-ethernet adapter for second interface. They connected to whitebeet seperately.

**To Reproduce**
>2 different FreeV2G folder
>run 1 script in first folder. Start with eth0 for example.
> When first script starts charging run second folder's sciprt. With eth1.
> Charging starts but 30 second later its stop.

**Expected behavior**
We expect 2 EVs charging properly.

**Logs**
[wireshark.zip](https://github.com/Sevenstax/FreeV2G/files/14084271/wireshark.zip)

**Comment by lho-stx** [comment]
Hey @sametyazici,

I checked your logs and indeed the first charging session looks fine to me. Now have a look into the communication between Whitebeet and Host controller and Whitebeet and EV of the failing session:

![2024-01-29-160219_2560x1440_scrot](https://github.com/Sevenstax/FreeV2G/assets/103272216/046eaee1-9e30-4372-a5af-cc39ddc34d75)

In frame 2947 the Whitebeet reports the EV has set it's control pilot to state B indicating an error. In frame 2957 the EV sends a session stop request, which the Whitebeet thinks is a sequence error (because normally there is a power delivery request before session stop).

The following image shows the currents and voltages requested/provided via V2G communication of the session. The measurement marker is set to the point right before the session failing:

![2024-01-29-155043_2560x1440_scrot](https://github.com/Sevenstax/FreeV2G/assets/103272216/d9a879e0-15f5-4c40-95f2-0a3373092bd1)

You can see, that the at the moment the session stops the EV requested 61.6A and the EVSE only provides 52A. Also the time the EVSE needs to get there is really long. I suspect that the mismatch between target current and provided current and the long time to get there is the reason why the EV thinks there is an error. There are constraints in the IEC 61851 regarding power delivery and timing. Please double check if you are meeting these requirements.

Best regards,
lho
