### ISSUE TITLE
Response code 0x10 for PI1.1

### ISSUE THREAD

**Issue by ahpo2019** [Sevenstax/FreeV2G#294]
**Your Question**
Ask your questions here.
After send a start chargign command(0xAC), update DC parameters response code change from 0x00(MISO transfers, 55 55 00 00 C0 27 A3 0B 00 01 00 A6 C1) to 
0x10(MISO transfers, 55 55 00 00 C0 27 A3 13 00 01 10 8E C1). What is the meaning for this response code? Thank you. 

PI1.1 fw version: 1_0_0_7

**Comment by lho-stx** [comment]
Hey @ahpo2019,

The response code 0x10 means that setting the parameters failed, because of a wrong combination/value range of the parameters. In this specific case the paramters are invalid if the SOC has a value greater than 100, the EvStatus is not in the range from 0 to 7 (inclusive) or you are actually doing an AC charging session but trying to update the DC charging parameters.

Please double check the update DC charging parameters message and if you are actually conducting a DC charging session. If the everything is ok and the issue still persists, please open a new ticket using the "bug report" issue template and provide all log files asked for.

Best regards,
lho
