### ISSUE TITLE
cable check not receive

### ISSUE THREAD

**Issue by nikunjp26** [Sevenstax/FreeV2G#327]
Platform: EVSE
Firmware Version: i.e. V02_01_00 with retransition patch
Host Controller Interface: Ethernet
Host: Own Implementation

**Dear Team**

Please check the UART and Wireshark logs as per below snapshot and tell us the reason why cable check request was not getting from bus side and provide the solution of this.

![image](https://github.com/Sevenstax/FreeV2G/assets/31069430/8cf76391-df29-49a6-9f12-e35d002da7d8)

[cable-check-not-receive.zip](https://github.com/user-attachments/files/15805401/cable-check-not-receive.zip)

**Best Regards,
Nikunj Patel**

**Comment by lho-stx** [comment]
Hey @nikunjp26,

there are multiple charging sessions of multiple WHITE Beets in this log file.

## WHITE Beet 1 Session 1

This session shows the exact same behavior of the PEV (wrong sequence numbers, missing packet and timeout) as in the second charging session of #323, but this time after the ChargeParameterDiscoveryResponse.

![327_wb1_session1](https://github.com/Sevenstax/FreeV2G/assets/103272216/79c03352-35cf-4f45-984d-1c1cb2d579b7)

## WHITE Beet 1 Session 2

Same behavior of PEV, but no problem this time.

## WHITE Beet 2 Session 1

This session shows the exact same behavior of the PEV (wrong sequence numbers, missing packet and timeout) as in the second charging session of #323, but during the charge loop.

![327_wb2_session1](https://github.com/Sevenstax/FreeV2G/assets/103272216/1731ead7-cffd-4a62-b98f-74bd253ae649)

## WHITE Beet 2 Session 2

Same behavior of PEV, but no problem for this one.

As in #323 I do not have any advice (yet?).

But I have a request: Please try to keep the log files shorter and only include the communication of interest, e.g. filter out the WHITE Beet traffic your are not interested in and stop the recording after the failed charging session. Log files this big slow down the process, because we need to separate the communication in order to work with the files. Thank you!

Best regards,
lho
