### ISSUE TITLE
Question: The SPI_TX_PENDING is permanently high (3.3V) 

### ISSUE THREAD

**Issue by AdrianKn** [Sevenstax/FreeV2G#329]
**Before you post**
- [x] I confirm that I've read the [guide on how to post issues](https://github.com/Sevenstax/FreeV2G/issues/304)
- [x] I confirm that I've consulted the [wiki](https://github.com/Sevenstax/FreeV2G/wiki) about my issue

**Your Question**
Ask your questions here.

(https://github.com/Sevenstax/FreeV2G/issues/304)
- [x] I confirm that I've consulted the [wiki](https://github.com/Sevenstax/FreeV2G/wiki) about my issue

**Your Question**
Ask your questions here.

I am using a White Beet Carrier Board EI 1.1 and would like to control it via SPI using a SAMV71Q21B microcontroller.
As you can see in the next 4 oscilloscope images (Figure 1-4), the communication with the configuration commands and the corresponding responses works.  However, I have the following problem the pin SPI_TX_PENDING is permanently high (3.3V) when I try to read out the White Beet, it responds to me in the Size Exchange Frame with aa aa 00 00 which means that it cannot send me any messages (Figure 5). What could be the reason that the SPI_TX_PENDING is not set to low?
 
My second question is if I normally also read the responses via the SPI_TX_PENDING or if I should simply read them with a time delay after sending the configuration command (this is how I currently do it).
 
Channels:  Blue = Clk,, Green = CS, Yellow = MOSI, pink = MISO

1.
![Figure1](https://github.com/Sevenstax/FreeV2G/assets/174595479/5110f983-7683-4abb-b6b2-b5872d043c50)

2.
![Figure2](https://github.com/Sevenstax/FreeV2G/assets/174595479/05dc7fb2-1ac3-414a-8555-53e73b8727e8)

3.
![Figure3](https://github.com/Sevenstax/FreeV2G/assets/174595479/ccb4e76d-2b65-4fc3-b0df-5b2844ceee41)

4.
![Figure4](https://github.com/Sevenstax/FreeV2G/assets/174595479/ec52df21-561c-448a-9abd-a81169e57353)

5.
![Figure5](https://github.com/Sevenstax/FreeV2G/assets/174595479/d8410e2b-0bf2-4e23-8bd5-d4caab9a9200)

**Comment by lho-stx** [comment]
Hey @AdrianKn,

Thank you for using the template!

You should read the data only when the TX pending pin is high. Normally the TX_PENDING pin is only high when a framing message is ready to be polled by the host. Are you sure you are not setting the pin high by accident in your host application? Is the Pin high all the time, even with the host disconnected?

To really investigate this issue I kindly ask you to create a new issue using the ["bug report" template](https://github.com/Sevenstax/FreeV2G/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) and provide the log files asked for (e.g. real logic analyzer logs using a file format supported by us).

I will close this issue for now, because you will create a new one.

Thank you,
lho
