### ISSUE TITLE
SPI transaction breaks using "null" transaction

### ISSUE THREAD

**Issue by ElectronicMinds-uk** [Sevenstax/FreeV2G#48]
I have implemented the suggested solution from my previous ticket #29 .
This has led to a new problem in that after a few transactions the whitebeet returns error headers, instead of the normal 0x5555 they are 0xaaaa. The second header appears to be correct as it has a length included which the actual header does not.
Here is the SPI listing
![image](https://user-images.githubusercontent.com/57374096/159895135-4340343c-8435-4309-9627-1230a14b1c1d.png)
As you can see the transaction starting at line 21  has whitebeet returning incorrect headers.
I have lengthened the pause time to 500ms and the problem takes a couple of more transactions to occur but it still occurs.
I have tried terminating the host transaction with a 0xc1 but the behaviour is the same.

**Comment by jpo-stx** [comment]
Hi @ElectronicMinds-uk ,

first of all, sorry for the late response! What I see in the log at line 21 and 22 is that both the host and the WB do not want to send any data. Was the TX_PENDING line high at this point? Then in line 23 the host sends a dataframe, but there is nothing to be exchanged and the WB is not ignoring this dataframe.

1. Can you tell me what your setup is, are you using FreeV2G?
2. Have you implemented the timing requirements?
3. A timing diagram of the event would be helpful (lines 20-26)

The solution would be to send the size exchange frame again instead of the data exchange frame when there was a zero in the size of the size exchange frame.

I will try to reproduce this.

**Comment by lho-stx** [comment]
Hey @ElectronicMinds-uk,
as there is no progress in this issue it will be closed. If you still encounter this issue, please reopen!
Best regards,
lho
