### ISSUE TITLE
DC Charge Parameters Update Providing Wrong Payload Size

### ISSUE THREAD

**Issue by schmitzcj** [Sevenstax/FreeV2G#94]
**Setup details**
EV
Hardware: CODICO WB-CARRIER-BOARD-PI 1.1
Firmware: V01_00_04
Manual: 2.11.2

EVSE
Hardware: Vector vSECC Controller
Firmware: 2.5.1

**Problem**
Every time FreeV2G receives a Sub-ID 0xC1 (DC Charge Parameters Update) from the WHITE-Beet(WB), it does not know how to completely parse the message. The WB supplies a 25-byte message, however, FreeV2G is expecting a longer message. The manual's section for 0xC1 shows an example that says the payload size is 25 bytes. The example continues on to show a payload size of 36 bytes, causing some additional confusion. 

Should the WB be sending a 36-byte message(WB Firmware/Manual issue) or a 25-byte message(FreeV2G/Manual issue)?

Hex message received by FreeV2G in Whitebeet.v2gEvParseDCChargeParametersChanged():
00 00 00 
00 00 00 
00 00 00 
03 b6 00 
00 c8 00 
03 b6 00 
02 ee 00 
00 00 00 
00

FreeV2G parses the hex message as:
`{'evse_min_voltage': 0, 'evse_min_current': 0, 'evse_min_power': 0, 'evse_max_voltage': 950, 'evse_max_current': 200, 'evse_max_power': 950, 'evse_present_voltage': 750, 'evse_present_current': 0, 'evse_status': 0}`

Exception: "Less payload than expected!"

Thank you for your help!

**Comment by jpo-stx** [comment]
Hello @schmitzcj ,

It seems to me that you are not using the correct FreeV2G version for your Whitebeet firmware. Please use the correct FreeV2G tag for your Whitebeet version. There were parameters added to the "DC Charge Parameters Changed" message since 1.0.4.

I would advise to update the EV to the latest firmware version 1.0.6! If something is holding you back you can use the FreeV2G tag for your Whitebeet version: https://github.com/Sevenstax/FreeV2G/tree/EV_v1.0.4_0
